trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Images'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'VivaWalletProjects'
    repository: 'vivawalletproject' 
    tags: 
      user-service:$(Build.BuildId)
      order-service:$(Build.BuildId)
      payment-service:$(Build.BuildId)
- task: KubernetesManifest@0
  displayName: 'Deploy to Kubernetes'
  inputs:
    command: 'apply'
    manifests: |
      k8s/user-service.yaml
      k8s/order-service.yaml
      k8s/payment-service.yaml

