trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Images'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'VivaWalletProjects'
    repository: 'vivawalletproject' 
    tags: 
      user-service:$(Build.BuildId)
      order-service:$(Build.BuildId)
      payment-service:$(Build.BuildId)

