trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'VivaWalletProjects'
    command: 'login'

- task: Docker@2
      inputs:
        containerRegistry: 'VivaWalletProjects'
        repository: 'vivawalletproject'
        command: 'build'
        Dockerfile: '**/Dockerfile'