trigger:
- main

variables:
  - name: imageName
    value: 'vivaimage'
  - name: containerRegistry
    value: 'vivawalletproject'
  - name: repository
    value: 'ipapadod/vivawalletproject'
  - name: sshEndpoint
    value: 'VivaVirtualMachine'


stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Installing required packages"
        python3 -m venv env
        source env/bin/activate
        pip install -r deployments/requirements.txt
    - script: |
        echo "Testing the project"
        python -m unittest discover -s src/ -p "*.py"
      displayName: 'Test the project'    
    - script: |
        echo "Running test services"
        python -m unittest discover -p 'tests/test_*.py' -v
    - script: |
        echo "Building the Docker image"
        docker build -t $(imageName) .
        echo "Running unit tests"
        python -m unittest src/main.py
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'results/test-results.xml'
    - task: Docker@2
      inputs:
        command: 'build'
        containerRegistry: '$(containerRegistry)'
        repository: '$(repository)'
        tags: '$(Build.BuildId)'
        Dockerfile: 'deployments/Dockerfile'
    - task: Docker@2
      inputs:
        command: 'push'
        containerRegistry: '$(containerRegistry)'
        repository: '$(repository)'
        tags: '$(Build.BuildId)'


- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CopyFiles@2
            inputs:
              sourceFolder: '$(System.DefaultWorkingDirectory)'
              targetFolder: '/home/testingsViva'
              cleanTargetFolder: true
              copyOptions: '-p'
              contents: |
                myimage.tar
          - task: SSH@0
            inputs:
              sshEndpoint: '$(sshEndpoint)'
              scriptSource: 'inline'
              inlineScript: |
                sudo docker pull vivaimage
                sudo docker run -d -p 59790:59790 vivaimage
                #docker pull <image-name>:<image-tag>
                #docker tag <image-name>:<image-tag> <new-image-name>:<new-image-tag>
                #docker save -o <new-image-name>.tar <new-image-name>:<new-image-tag>
                #sudo docker-compose up -d


- stage: Deploy1
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              command: 'apply'
              namespace: 'default'
              yaml: |
                apiVersion: v1
                kind: Service
                metadata:
                  name: vivawalletproject-service
                spec:
                  selector:
                    app: vivawalletproject
                  ports:
                  - name: http
                    port: 80
                    targetPort: 80
          - task: Kubernetes@1
            inputs:
              command: 'apply'
              namespace: 'default'
              yaml: |
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: vivawalletproject-deployment
                spec:
                  replicas: 3
                  selector:
                    matchLabels:
                      app: vivawalletproject
                  template:
                    metadata:
                      labels:
                        app: vivawalletproject
                    spec:
                      containers:
                      - name: vivawalletproject
                        image: '$(containerRegistry)/$(repository):$(Build.BuildId)'
                        ports:
                        - containerPort: 80
