trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage:Build
  displayname: Build Image
  jobs:
  -  job: Build
     displayName: Build
     pool:
       vmImage: 'ubuntu-latest'
     steps:
     -task: Docker@2
      displayName: Build and Push
      inputs:
        command: build and Push
        containerRegistry: 'VivaWalletProjects'
        repository: 'vivawalletproject' 