trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'VivaWalletProjects'
    repository: 'vivawalletproject'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'