trigger:
- master


variables:
  tag: '$(Build.BuildId)'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'VivaWalletProjects'
    dockerComposeFile: 
    action: 'Build services'

